[face.detection]
min_face_size = 64
max_face_size = 800
scale_factor = 1.2
min_neighbors = 3
confidence_threshold = 0.4
use_gray = true
image_scale = 0.8

[face.recognition]
threshold = 0.55
outlier_threshold = 0.3
outlier_iter = 2

[monitoring]
interval = 0
mosaic_style = """
{
    position: absolute;
    /* 深肉色网格线 + 淡肉色底色，大网格 */
    background:
      linear-gradient(rgba(201,126,99,0.35) 2px, transparent 2px),
      linear-gradient(90deg, rgba(201,126,99,0.35) 2px, transparent 2px),
      #F5D7C6;
    background-size: 32px 32px, 32px 32px, cover;
    background-position: 0 0, 0 0, 0 0;
    background-blend-mode: normal, normal, normal;
    backdrop-filter: none;
    -webkit-backdrop-filter: none;
    box-shadow: inset 0 0 0 0.5px rgba(0,0,0,0.06);
    border: 0;
    border-radius: 6px;
    pointer-events: none;
    z-index: 9999;
    opacity: 1;
}
"""

[system]
log_level = "info"